### ISSUE TITLE
Hosting av media-filer

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/staut#12]
Om vi oppretter et repository som heter "RosenborgSupporterSoftware.github.com", så kan vi lage en presentasjonsside for RosenborgSupporterSoftware som får URL RosenborgSupporterSoftware.github.io. Det fungerer i alle fall sånn for person-brukere, men jeg har ikke verifisert at det fungerer likedan for team dog. Men gitt at det går. Jeg har sett det foreslått at om man f.eks. vil ha screenshots i README.md-presentasjonen så kan man commit'e de til sitt github.io repo og referere de fra README.md. Se http://www.jefclaes.be/2012/04/add-images-to-github-readme.html

Det jeg tenkte var at det var en løsning som kanskje kan misbrukes til å hoste helt vilkårlige media-filer. Jeg har ikke sjekket om Referer-headeren sjekkes ennå og vil blokkere referanser fra rbkweb.no dog - det kan jo hende det blokkeres. I tillegg er kanskje ikke dynamisk/periodisk oppdaterte grafikkfiler det best egnede for et git-repository (pluss at det er en delay på noen minutter fra du commit'er til repo.github.com-repositoryet til github.io-sidene faktisk oppdateres), så seteteller-grafen er kanskje ikke best egnet. Alt av statisk grafikk burde være kurrant dog. For min del vil det være headshots av spillerene og klubblogoer og slikt i såfall - STAut har kanskje ikke så mye slike behov?

I tillegg kan vi jo presentere STAut og Storkar på sider i det repoet, og bruke det om vi vil ha screenshots lagt inn i README.md selvsagt...

**Comment by havremunken** [comment]
Liker idéen om å bruke det - det er vel sikkert ikke vanskelig å sørge for å git-comitte og pushe nylig oppdaterte grafer heller, men det spørs jo da på ev. blokkering og forsinkelse som du nevner. 

For STAut sin del så vil jo den også trenge logoer til lagene vi møter - ihvertfall hvis designet blir noe i nærheten av det jeg dodler med nå. Da kan det vel være greit at vi har et standardisert sted å putte sånne ting som ikke oppdaterer seg veldig ofte. STAut vil jo typisk dra det inn og bruke det i generering av sitt eget bitmap, så RBKweb-brukere som går inn på en kamptråd vil kun hente dette statiske bildet og ikke logoene o.l. direkte. 

Vi har vel for øyeblikket følgende opsjoner for hosting av de genererte bildene:

1) Github pages. Kanskje litt tregt å oppdatere, men gratis og "for alltid".

2) Azure som en del av hele webløsningen. Ikke gratis, men Nils Georg har da tilgang på ressurser via MSDN som gjør at vi ikke betaler for det. Kan jo dog hende at det en gang i fremtiden kommer andre prosjekter han heller vil bruke dette til.

3) Dropbox e.l. - så lenge det kjører på kottserveren min er dette et alternativ. Har konto via jobb så latterlig mye lagringsplass. Vet ikke helt hvordan vi skal få filer fra Azure til DropBox om vi ikke kjører på egen VM, men det er sikkert mulig.

4) Kottserver. F.eks. har Hedon på RBKweb stilt seg til disp. 

For alt jeg vet finnes det også gratis CDN-servere o.l. hvis man ikke har store behov (blir jo ikke uendelig mange MB av dette i løpet av en sesong). Men vi har jo også god tid til å vurdere hva som funker bra for oss!

**Comment by larsjaas** [comment]
Da har jeg sjekket om Referer er noe problem, noe det viste seg å ikke være. Min lille test fungerte uten problemer i alle fall.

Jeg tror ikke git er spesielt egnet for binærfiler som endres, så om det skjer mye er det mulig at historikken vil ta uforholdsmessig mye plass. Dersom vi finner ut at repoet tar plagsomt mye plass lokalt etterhvert, tror jeg vi kan løse det ved å bare slette repositoriet og gjenopprette det på nytt fra siste utsjekk og med null historikk, og la alle som jobber med det klone det fra github på nytt...

**Comment by larsjaas** [comment]
Lukker denne siden den er på staut-repoet, så får vi diskutere skikk og bruk på issues/wiki for github.io-repoet.
