### ISSUE TITLE
Klarer ikke å hente data fra Odd-kampen

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#23]
Nytt dataformat på websiden?

```
E:\staut\java>"C:\Program Files\Java\jre1.8.0_121\bin\java.exe" -jar .\dist\lib\
STAut.jar --collector
INFO: System file encoding: Cp1252
INFO: Loading configuration from E:\staut\java\dist\lib\configuration.properties

INFO: Extracting event information from URL: http://www.ticketmaster.no/event/51
5827
ERR: Could not find relevant event details for event. ID: 515827
Name: null
Date: null
Time: null
Location: null
Competition: null
Round: 0
Code: null
AvailabilityURL: null
GeometryURL: null
EventURL: http://www.ticketmaster.no/event/515827
INFO: Updating event collections.
INFO: Failed to find availabilityURL for event eventId: 515827
INFO: Most likely internet sale has not yet started.
INFO: All details we could collect: ID: 515827
Name: null
Date: null
Time: null
Location: null
Competition: null
Round: 0
Code: null
AvailabilityURL: null
GeometryURL: null
EventURL: http://www.ticketmaster.no/event/515827
```

Tagger @vemundo her som vel er den som får dritten i sånne sammenhenger... ;)

Jeg får hentet ut data manuelt når jeg "use the source" og snekrer availabilityUrl manuelt.

**Comment by vemundo** [comment]
Sitter i en møte-serie på jobb, skal se på det når jeg kommer hjem rundt
17ish

**Comment by havremunken** [comment]
Tipp topp tommel opp, er ikke SÅ mye spennende utvikling de første timene av grafen uansett. :)

**Comment by vemundo** [comment]
Har pushet endringer nå som virker hjemme hos meg iallefall. De hadde endret omtrent alt av hvor informasjon kunne finnes på websiden, så ikke umulig at det er noe mer som må fikses, men la ikke merke til noe.

**Comment by havremunken** [comment]
Det funka her også, så vi stenger denne nå, så hører vi det helt sikkert om noe blir plukket opp feil underveis! :)

Takker for kjapp respons som alltid!
