### ISSUE TITLE
Filnavn på nedlastede xml-filer

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#4]
Nå er jeg kjip på å lage issues her.. :) Prøver bare å venne meg til en workflow der jeg ikke er alene i verden.

Som nevnt i issue #3 så fikk jeg det nå til å kjøre. Men som vi var inne på elsewhere - Windows er ikke dritglad i kolon i filnavn.

Så når collectoren nå laster ned denne:

Downloading into: .\archive\2015_467263_Vikingur E\467263_Vikingur E_2015-06-27T00:40.xml

så blir fila på filsystemet hetende:

467263_Vikingur E_2015-06-27T00

Ikke noe "filetternavn" e.l.

Dette er selvfølgelig ikke noe dramatisk, men kanskje en tanke å ha tiden som 0040 istedenfor 00:40? Så lenge vi er enige om å holde oss til denne strukturen blir vel ikke det noe problem?

<bs-eventid>_<motstander><ev turnering>_<år>-<måned>-<dag>THHMM.xml

Nå er jeg trøtt som en dupp og full av vondskap ifm. smurfekampen i om bare 17 timer, men er det problemer her jeg ikke ser? Bortsett fra at det er kjedelig å både lage formatet og parse det, men sånn er det vel stort sett med strings. :)

**Comment by havremunken** [comment]
Kan nevne som en halvkomisk konsekvens av dette - halvparten av filene blir "borte". Siden filnavnet stopper ved kolonet blir de to filnavnene innenfor den samme timen (kjører med default intervall) like, og den siste overskriver da den første.

Ingen krise, bare synes dette var moro. Sikkert fordi jeg er nervøs. :)

**Comment by havremunken** [comment]
Litt mer "alvorlig" greie jeg akkurat la merke til - filene som lastes ned er tomme. 0 bytes.

Noe jeg kan gjøre for å vise hva som skjer? Noe logging e.l. som kan gjøres?

eventinfo.properties-fila har innhold, så programmet får lov til å skrive ting til disk ihvertfall.

**Comment by vemundo** [comment]
Ah, tilbake etter et par dager offline med Smurfeblues. Skal se på dette,
filnavnet skal være kjapt fikset.

Tomme filer høres jo mystisk ut. Det er ikke mer output å få ut, --silent
gir mindre. :)
Men jeg kan legge inn noe debug.

Går an å prøve å kjøre "--download-next --output=<fil>" istedet for
"--collector". Da skal den laste ned en fil for neste kamp bare.

Du ser alle opsjoner med:

> java -jar dist/lib/STAut.jar
> --collector                 Start the automated data collector
> --config                    List application configuration data
> --download-next             download availability data for next active event
> --download-all              download availability data for all active events
> --dump                      Dump raw data on availability
> --input=<file>              Load availability data from input file
> --output=<directory>        Store decoded availability data in output
> directory
> --report-diff               Print difference in ticktets for two event files
> --report-intersection       Print intersection in tickets for two event
> files
> --report-hold               Print data on seats with status 'hold'
> --report-open               Print data on seats with status 'open'
> --report-season-tickets     Print data on season tickets
> --report-section[=<sec>]    Print ticket data sorted by stadium section
> [for section sec]
> --report-sold               Print data on seats with status 'sold'
> --report-summary            Print summary report
> --report-ticket[=<ETT>]     Print section data sorted by ticket type [for
> specific ticket type ETT]
> --report-unkown             Print data on seats with status 'unknown'
> --silent                    No information printed, only report data

Vemund

2015-06-27 14:22 GMT+02:00 Rune Jacobsen notifications@github.com:

**Comment by vemundo** [comment]
Har fikset problemet med filnavnet, byttet : med -, synes det er litt mer leselig enn ingen separator.

Pushet også en liten endring som skriver ut antall bytes lastet ned og også litt ekstra feilhåndtering under nedlasting, så får vi se om det hjelper oss nærmere hvorfor du får ned tomme filer.

**Comment by havremunken** [comment]
Da funka alt mye bedre! 

```
PS E:\staut\java> & 'C:\Program Files\Java\jre1.8.0_45\bin\java.exe' -jar .\dist\lib\STAut.jar --collector
INFO: Loading configuration from E:\staut\java\dist\lib\configuration.properties
INFO: Updating event collections.
INFO: Starting collection of URL: http://www.billettservice.no/seatmap/proxy/availability/NO/TLDEC01-2015,NO-467263.xml every 30 minutes.
INFO: Starting collection of URL: http://www.billettservice.no/seatmap/proxy/availability/NO/TLD0815-2015,NO-438523.xml every 30 minutes.
INFO: Downloading into: .\archive\2015_EC_1_Vikingur_467263\467263_Vikingur_2015-06-30T12-12.xml
INFO: Starting collection of URL: http://www.billettservice.no/seatmap/proxy/availability/NO/TLD0915-2015,NO-438525.xml every 30 minutes.
INFO: Downloading into: .\archive\2015_LEAGUE_8_Odd_438523\438523_Odd_2015-06-30T12-12.xml
INFO: Downloading into: .\archive\2015_LEAGUE_9_Sarpsborg_438525\438525_Sarpsborg_2015-06-30T12-12.xml
INFO: Finished downloading: .\archive\2015_LEAGUE_9_Sarpsborg_438525\438525_Sarpsborg_2015-06-30T12-12.xml (64690 bytes)
INFO: Finished downloading: .\archive\2015_EC_1_Vikingur_467263\467263_Vikingur_2015-06-30T12-12.xml (39102 bytes)
INFO: Finished downloading: .\archive\2015_LEAGUE_8_Odd_438523\438523_Odd_2015-06-30T12-12.xml (67074 bytes)
```

..og nå har også filene innhold!

Kan det ha vært kolon i filnavnet som lagde krøll? Forøvrig helt enig at en separator mellom timer og minutter er fint å ha. 

Full fest!

**Comment by vemundo** [comment]
Hehe, flott! Ja, jeg gjorde ikke noe annet lurt enn ekstra feilsjekking og å summere opp antall bytes jeg lesser over, så må nesten ha vært filnavnet.
