### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by nilsgs** [RosenborgSupporterSoftware/staut#9]
Hei, jeg har såvidt begynt å sette opp et API. Bare til informasjon slik at vi ikke går i beina på hverandre.

**Comment by havremunken** [comment]
Awesome :) Bare av nyskjerrighet - er det Web API-saken til MS du bruker? Jeg har så vidt snust på den før de "slo sammen" MVC og den, og har ikke fulgt med på navneendringer o.l., men er spent på hvordan den er å bruke.

Antar at første "store" greie for denne blir å ramse opp punkter på graf til frontend-app'en når den finnes.

Har fungerende kode som leser inn filer og legger inn i databasen nå, så generering av statisk graf bør ikke være langt unna!

**Comment by nilsgs** [comment]
Det er Web API ja. Har committet en versjon nå. Først og fremst oppsett, IoC osv, og en kontroller som wrapper IEventRepository (foreløpig mot en dummy implementasjon).

**Comment by havremunken** [comment]
Bare sett så vidt på det, men dette ser jo veldig enkelt og greit ut å forholde seg til. Har aldri brukt Autofac før (kun Ninject), men når man kan definere bindingene i kode som du har gjort her gjør det jo ingenting - det er trivielt å forstå hva som foregår.

Har forøvrig også tenkt på om jeg skulle lage en in-memory-implementasjon av repositoriene som du har gjort med dummyen her, rett og slett for å gjøre integrasjonstester mer behagelig. Objektet som spiser data fra disk og legger i databasen er relativt testbart, men ikke godt testet foreløpig. Det forholder seg stort sett til interfaces, men for å gjøre livet verdt å leve kan det være at en ordentlig List<T>-basert implementasjon kan være bedre å forholde seg til enn en mock. Vi får se.

Uansett, spennende opplegg!
